import type {
  Client,
  Driver,
  DriverCredential,
  DtcAlert,
  FleetVehicle,
  FuelRouteStat,
  HosLogEntry,
  Incident,
  Invoice,
  PartItem,
  PmReminder,
  Rider,
  Trip,
} from "./types";

export const communities = [
  "Thompson",
  "Leaf Rapids",
  "Lynn Lake",
  "South Indian Lake",
  "Black Sturgeon Falls",
];

export const trips: Trip[] = [
  {
    id: "TR-4821",
    date: "Jul 7",
    win: "06:30 → 09:55",
    svc: "alamos",
    from: "Thompson",
    to: "Lynn Lake",
    stops: ["Thompson", "Leaf Rapids", "Lynn Lake"],
    km: 198,
    driver: "D. Chartrand",
    vehicle: "INT-3000 · U-02",
    cap: "18 / 24",
    status: "In progress",
    sk: "info",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    open: false,
  },
  {
    id: "TR-4822",
    date: "Jul 7",
    win: "07:15 → 09:40",
    svc: "nihb",
    from: "South Indian Lake",
    to: "Thompson",
    stops: ["South Indian Lake", "Thompson"],
    km: 220,
    driver: "M. Okimaw",
    vehicle: "Transit T-150 · U-04",
    cap: "3 / 7",
    status: "In progress",
    sk: "info",
    client: "NIHB",
    po: "VCH-88041",
    open: false,
  },
  {
    id: "TR-4823",
    date: "Jul 7",
    win: "11:00 → 14:20",
    svc: "community",
    from: "Leaf Rapids",
    to: "Thompson",
    stops: ["Leaf Rapids", "Thompson"],
    km: 174,
    driver: null,
    vehicle: "Transit T-150 · U-05",
    cap: "4 / 7",
    status: "Open — needs coverage",
    sk: "soon",
    client: "Community",
    po: "—",
    open: true,
  },
  {
    id: "TR-4824",
    date: "Jul 7",
    win: "13:30 → 16:10",
    svc: "alamos",
    from: "Lynn Lake",
    to: "Thompson",
    stops: ["Lynn Lake", "Leaf Rapids", "Thompson"],
    km: 198,
    driver: "D. Chartrand",
    vehicle: "INT-3000 · U-02",
    cap: "empty return",
    status: "Empty leg available",
    sk: "off",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    open: false,
  },
  {
    id: "TR-4825",
    date: "Jul 7",
    win: "15:00 → 17:35",
    svc: "grocery",
    from: "Thompson",
    to: "Black Sturgeon Falls",
    stops: ["Thompson", "Black Sturgeon Falls"],
    km: 142,
    driver: null,
    vehicle: "Transit T-150 · U-06",
    cap: "load 62%",
    status: "Open — needs coverage",
    sk: "soon",
    client: "Grocery Program",
    po: "—",
    open: true,
  },
  {
    id: "TR-4826",
    date: "Jul 7",
    win: "16:45 → 20:05",
    svc: "charter",
    from: "Thompson",
    to: "Lynn Lake",
    stops: ["Thompson", "Lynn Lake"],
    km: 198,
    driver: "K. Beardy",
    vehicle: "INT-3000 · U-03",
    cap: "11 / 24",
    status: "Scheduled",
    sk: "ontime",
    client: "Keewatin Tribal Council",
    po: "CH-3390",
    open: false,
  },
  {
    id: "TR-4818",
    date: "Jul 7",
    win: "05:10 → 08:30",
    svc: "community",
    from: "Black Sturgeon Falls",
    to: "Thompson",
    stops: ["Black Sturgeon Falls", "Thompson"],
    km: 142,
    driver: "J. Spence",
    vehicle: "Transit T-150 · U-04",
    cap: "6 / 7",
    status: "Completed",
    sk: "ontime",
    client: "Community",
    po: "—",
    open: false,
  },
  {
    id: "TR-4827",
    date: "Jul 7",
    win: "18:20 → 21:00",
    svc: "cargo",
    from: "Thompson",
    to: "Leaf Rapids",
    stops: ["Thompson", "Leaf Rapids"],
    km: 96,
    driver: null,
    vehicle: "unassigned",
    cap: "—",
    status: "Open — no eligible driver",
    sk: "over",
    client: "Parcel",
    po: "—",
    open: true,
  },
];

export const drivers: Driver[] = [
  {
    id: 1,
    name: "D. Chartrand",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    dutyStatus: "On Duty",
    hos: "4h 20m",
    hk: "soon",
    lic: "Class 4 · exp 2027-03",
    lk: "ontime",
    dvir: "Passed",
    clr: ["Alamos ✓", "NIHB ✓"],
    phone: "(204) 555-0148",
    trips: 214,
  },
  {
    id: 2,
    name: "M. Okimaw",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    dutyStatus: "On Duty",
    hos: "6h 05m",
    hk: "ontime",
    lic: "Class 4 · exp 2026-11",
    lk: "ontime",
    dvir: "Passed",
    clr: ["NIHB ✓"],
    phone: "(204) 555-0192",
    trips: 98,
  },
  {
    id: 3,
    name: "K. Beardy",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    dutyStatus: "Driving",
    hos: "9h 40m",
    hk: "ontime",
    lic: "Class 4 · exp 2028-01",
    lk: "ontime",
    dvir: "Passed",
    clr: ["Alamos ✓", "NIHB ✓"],
    phone: "(204) 555-0177",
    trips: 301,
  },
  {
    id: 4,
    name: "J. Spence",
    src: "Northern Link",
    duty: "Off duty",
    dk: "off",
    dutyStatus: "Off Duty",
    hos: "0h 00m",
    hk: "off",
    lic: "Class 4 · exp 2026-08",
    lk: "soon",
    dvir: "Passed",
    clr: ["NIHB ✓"],
    phone: "(204) 555-0110",
    trips: 156,
  },
  {
    id: 5,
    name: "T. Miller",
    src: "Miller the Mover",
    duty: "On duty",
    dk: "info",
    dutyStatus: "On Duty",
    workPermit: true,
    hos: "2h 15m",
    hk: "soon",
    lic: "Class 4 · exp 2027-06",
    lk: "ontime",
    dvir: "Passed",
    clr: ["Alamos ✓"],
    phone: "(204) 555-0201",
    trips: 44,
  },
  {
    id: 6,
    name: "R. Flett",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    dutyStatus: "On Duty",
    hos: "7h 30m",
    hk: "ontime",
    lic: "Class 4 · exp 2026-07",
    lk: "over",
    dvir: "Passed",
    clr: [],
    phone: "(204) 555-0139",
    trips: 187,
  },
  {
    id: 7,
    name: "A. Nepinak",
    src: "Miller the Mover",
    duty: "Deactivated",
    dk: "over",
    dutyStatus: "Off Duty",
    workPermit: true,
    hos: "—",
    hk: "off",
    lic: "Class 4 · exp 2027-09",
    lk: "ontime",
    dvir: "Under review",
    clr: [],
    phone: "(204) 555-0166",
    trips: 72,
  },
];

// Driver credentials — MOCK ONLY, keyed by driverId (mirrors documents/insp by
// unit). Today ≈ 2026-07-17: `k` is hand-seeded from expiry (over = expired,
// soon = within ~60d, ontime = valid) so roster + detail alerts light up.
export const driverCredentials: DriverCredential[] = [
  // 1 — D. Chartrand
  { id: "CRD-1001", driverId: 1, type: "Licence Class", label: "Class 4", issued: "2023-03-01", expiry: "2027-03-15", k: "ontime" },
  { id: "CRD-1002", driverId: 1, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2025-08-01", expiry: "2026-08-20", k: "soon" },
  { id: "CRD-1003", driverId: 1, type: "Drug & Alcohol", label: "Pre-employment + random pool", issued: "2025-11-01", expiry: "2026-11-30", k: "ontime" },
  { id: "CRD-1004", driverId: 1, type: "First Aid", label: "Standard First Aid + CPR-C", issued: "2024-05-01", expiry: "2027-05-01", k: "ontime", optional: true },
  // 2 — M. Okimaw
  { id: "CRD-1010", driverId: 2, type: "Licence Class", label: "Class 4", issued: "2022-11-01", expiry: "2026-11-30", k: "ontime" },
  { id: "CRD-1011", driverId: 2, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2026-01-01", expiry: "2027-01-15", k: "ontime" },
  { id: "CRD-1012", driverId: 2, type: "Drug & Alcohol", label: "Random pool", issued: "2025-09-01", expiry: "2026-09-10", k: "soon" },
  // 3 — K. Beardy
  { id: "CRD-1020", driverId: 3, type: "Licence Class", label: "Class 2", issued: "2024-01-01", expiry: "2028-01-10", k: "ontime" },
  { id: "CRD-1021", driverId: 3, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2025-06-01", expiry: "2027-06-01", k: "ontime" },
  { id: "CRD-1022", driverId: 3, type: "Drug & Alcohol", label: "Random pool", issued: "2025-02-01", expiry: "2027-02-01", k: "ontime" },
  { id: "CRD-1023", driverId: 3, type: "First Aid", label: "Standard First Aid + CPR-C", issued: "2023-09-01", expiry: "2026-09-05", k: "soon", optional: true },
  // 4 — J. Spence
  { id: "CRD-1030", driverId: 4, type: "Licence Class", label: "Class 4", issued: "2022-08-01", expiry: "2026-08-31", k: "soon" },
  { id: "CRD-1031", driverId: 4, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2025-03-01", expiry: "2027-03-01", k: "ontime" },
  { id: "CRD-1032", driverId: 4, type: "Drug & Alcohol", label: "Random pool", issued: "2025-12-01", expiry: "2026-12-15", k: "ontime" },
  // 5 — T. Miller (work permit)
  { id: "CRD-1040", driverId: 5, type: "Licence Class", label: "Class 1", issued: "2024-06-01", expiry: "2027-06-15", k: "ontime" },
  { id: "CRD-1041", driverId: 5, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2026-01-01", expiry: "2027-01-01", k: "ontime" },
  { id: "CRD-1042", driverId: 5, type: "Drug & Alcohol", label: "Random pool", issued: "2025-08-01", expiry: "2026-08-05", k: "soon" },
  { id: "CRD-1043", driverId: 5, type: "Work Permit", label: "LMIA work permit", issued: "2025-04-30", expiry: "2027-04-30", k: "ontime", optional: true, note: "Sponsor: Miller the Mover" },
  // 6 — R. Flett (expired licence)
  { id: "CRD-1050", driverId: 6, type: "Licence Class", label: "Class 4", issued: "2021-07-01", expiry: "2026-07-05", k: "over" },
  { id: "CRD-1051", driverId: 6, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2025-02-01", expiry: "2027-02-01", k: "ontime" },
  { id: "CRD-1052", driverId: 6, type: "Drug & Alcohol", label: "Random pool", issued: "2025-09-01", expiry: "2026-09-01", k: "soon" },
  // 7 — A. Nepinak (deactivated — lapsed permit + checks)
  { id: "CRD-1060", driverId: 7, type: "Licence Class", label: "Class 4", issued: "2023-09-01", expiry: "2027-09-01", k: "ontime" },
  { id: "CRD-1061", driverId: 7, type: "Police Record Check", label: "Criminal Record + Vulnerable Sector", issued: "2024-05-01", expiry: "2026-05-15", k: "over" },
  { id: "CRD-1062", driverId: 7, type: "Drug & Alcohol", label: "Random pool", issued: "2024-06-01", expiry: "2026-06-20", k: "over" },
  { id: "CRD-1063", driverId: 7, type: "Work Permit", label: "LMIA work permit", issued: "2024-07-01", expiry: "2026-07-01", k: "over", optional: true, note: "Permit lapsed — driver deactivated" },
];

// Hours-of-Service logs — MOCK ONLY, keyed by driverId. Mixes Driver-App
// (electronic) and Manual (paper backup) entries, per the same source split the
// Fleet DVIR prototype uses. Manual rows carry an enteredBy dispatcher name.
export const hosLogs: HosLogEntry[] = [
  // 1 — D. Chartrand
  { id: "HOS-2001", driverId: 1, date: "2026-07-16", duty: "Driving", onDutyH: 9.5, drivingH: 8, offDutyH: 10, source: "Driver App" },
  { id: "HOS-2002", driverId: 1, date: "2026-07-15", duty: "On Duty", onDutyH: 6, drivingH: 4.5, offDutyH: 12, source: "Driver App" },
  { id: "HOS-2003", driverId: 1, date: "2026-07-14", duty: "On Duty", onDutyH: 8, drivingH: 6, offDutyH: 10, source: "Manual (paper backup)", enteredBy: "Dispatch — L. Moose", note: "App offline in Leaf Rapids — logged on paper" },
  // 2 — M. Okimaw
  { id: "HOS-2010", driverId: 2, date: "2026-07-16", duty: "On Duty", onDutyH: 6, drivingH: 4.5, offDutyH: 12, source: "Driver App" },
  // 3 — K. Beardy
  { id: "HOS-2020", driverId: 3, date: "2026-07-17", duty: "Driving", onDutyH: 10, drivingH: 8.5, offDutyH: 9.5, source: "Driver App" },
  { id: "HOS-2021", driverId: 3, date: "2026-07-16", duty: "Driving", onDutyH: 9, drivingH: 7, offDutyH: 11, source: "Driver App" },
  { id: "HOS-2022", driverId: 3, date: "2026-07-15", duty: "On Duty", onDutyH: 5, drivingH: 3, offDutyH: 13, source: "Manual (paper backup)", enteredBy: "Dispatch — L. Moose" },
  // 4 — J. Spence
  { id: "HOS-2030", driverId: 4, date: "2026-07-16", duty: "Off Duty", onDutyH: 0, drivingH: 0, offDutyH: 24, source: "Driver App" },
  { id: "HOS-2031", driverId: 4, date: "2026-07-14", duty: "On Duty", onDutyH: 7, drivingH: 5, offDutyH: 11, source: "Driver App" },
  { id: "HOS-2032", driverId: 4, date: "2026-07-13", duty: "Driving", onDutyH: 9, drivingH: 7.5, offDutyH: 10, source: "Manual (paper backup)", enteredBy: "Dispatch — R. Sinclair" },
  // 5 — T. Miller
  { id: "HOS-2040", driverId: 5, date: "2026-07-16", duty: "On Duty", onDutyH: 8, drivingH: 6, offDutyH: 11, source: "Driver App" },
  { id: "HOS-2041", driverId: 5, date: "2026-07-15", duty: "Driving", onDutyH: 9.5, drivingH: 8, offDutyH: 10, source: "Manual (paper backup)", enteredBy: "Dispatch — R. Sinclair", note: "Contractor paper log submitted" },
  // 6 — R. Flett
  { id: "HOS-2050", driverId: 6, date: "2026-07-16", duty: "On Duty", onDutyH: 8.5, drivingH: 6.5, offDutyH: 10, source: "Driver App" },
  { id: "HOS-2051", driverId: 6, date: "2026-07-15", duty: "Driving", onDutyH: 9, drivingH: 7, offDutyH: 10.5, source: "Driver App" },
];

export const fleet: FleetVehicle[] = [
  {
    id: 1,
    unit: "U-02",
    model: "International 3000",
    seats: 24,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "NSC-11 due in 34d",
    ik: "ontime",
    plate: "MB · GHT 402",
    vin: "1HVBBAAN…4471",
    licReq: "Class 4",
    periodic: true,
  },
  {
    id: 2,
    unit: "U-03",
    model: "International 3000",
    seats: 24,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "NSC-11 due in 9d",
    ik: "soon",
    plate: "MB · GHT 418",
    vin: "1HVBBAAN…5522",
    licReq: "Class 4",
    periodic: true,
  },
  {
    id: 3,
    unit: "U-04",
    model: "Ford Transit T-150",
    seats: 7,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "Trip-inspection only",
    ik: "ontime",
    plate: "MB · FRT 771",
    vin: "1FTBW2CM…9013",
    licReq: "Class 4",
    periodic: false,
  },
  {
    id: 4,
    unit: "U-05",
    model: "Ford Transit T-150",
    seats: 7,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "Trip-inspection only",
    ik: "ontime",
    plate: "MB · FRT 802",
    vin: "1FTBW2CM…9188",
    licReq: "Class 4",
    periodic: false,
  },
  {
    id: 5,
    unit: "U-06",
    model: "Ford Transit T-150",
    seats: 7,
    status: "In maintenance",
    sk: "soon",
    dvir: "Passed today",
    dk: "ontime",
    insp: "Brake service",
    ik: "soon",
    plate: "MB · FRT 815",
    vin: "1FTBW2CM…9204",
    licReq: "Class 4",
    periodic: false,
  },
  {
    id: 6,
    unit: "U-01",
    model: "International 3000",
    seats: 24,
    status: "Out of service",
    sk: "over",
    dvir: "DVIR FAILED",
    dk: "over",
    insp: "Steering fault — critical",
    ik: "over",
    plate: "MB · GHT 390",
    vin: "1HVBBAAN…3310",
    licReq: "Class 4",
    periodic: true,
  },
];

// ---------------------------------------------------------------------------
// Maintenance & Asset Management previews — MOCK ONLY (no backend domain yet).
// Keyed by unit number so per-vehicle tabs in Fleet can slice them.
// ---------------------------------------------------------------------------

export const pmReminders: PmReminder[] = [
  { unit: "U-01", task: "Steering linkage inspection", basis: "time", due: "OVERDUE 6d", k: "over" },
  { unit: "U-01", task: "Engine oil & filter", basis: "mileage", due: "in 1,900 km", k: "ontime" },
  { unit: "U-02", task: "Engine oil & filter", basis: "mileage", due: "in 800 km", k: "soon" },
  { unit: "U-02", task: "Air brake adjustment check", basis: "time", due: "in 41d", k: "ontime" },
  { unit: "U-03", task: "Coolant flush", basis: "time", due: "in 34d", k: "ontime" },
  { unit: "U-03", task: "Differential fluid change", basis: "mileage", due: "in 6,200 km", k: "ontime" },
  { unit: "U-04", task: "Tire rotation", basis: "mileage", due: "in 2,400 km", k: "ontime" },
  { unit: "U-05", task: "Transmission service", basis: "hours", due: "in 40 engine-h", k: "soon" },
  { unit: "U-05", task: "Serpentine belt replacement", basis: "time", due: "in 12d", k: "soon" },
  { unit: "U-06", task: "Brake pads & rotors", basis: "mileage", due: "OVERDUE 350 km", k: "over" },
];

export const dtcAlerts: DtcAlert[] = [
  { unit: "U-01", code: "C0051", desc: "Steering wheel position sensor fault", severity: "Critical", k: "over", raised: "2d ago" },
  { unit: "U-06", code: "P0301", desc: "Cylinder 1 misfire detected", severity: "Major", k: "over", raised: "5h ago" },
  { unit: "U-05", code: "P0128", desc: "Coolant thermostat below regulating temp", severity: "Minor", k: "soon", raised: "1d ago" },
  { unit: "U-03", code: "P0456", desc: "EVAP system small leak detected", severity: "Minor", k: "soon", raised: "3d ago" },
  { unit: "U-02", code: "P1000", desc: "OBD readiness monitors incomplete", severity: "Info", k: "ontime", raised: "6d ago" },
];

export const partsInventory: PartItem[] = [
  { sku: "FLT-OIL-15W40", name: "Engine oil 15W-40 (20 L)", onHand: 6, min: 4, k: "ontime", loc: "Thompson shop · A2" },
  { sku: "BRK-PAD-INT30", name: "Brake pad set — International 3000", onHand: 1, min: 2, k: "over", loc: "Thompson shop · B1" },
  { sku: "FLT-AIR-T150", name: "Air filter — Transit T-150", onHand: 3, min: 3, k: "soon", loc: "Thompson shop · A4" },
  { sku: "BLB-HDL-H11", name: "Headlamp bulb H11 (pair)", onHand: 8, min: 4, k: "ontime", loc: "Thompson shop · C3" },
  { sku: "WPR-BLD-26", name: "Wiper blade 26\" winter", onHand: 2, min: 6, k: "over", loc: "Thompson shop · C1" },
  { sku: "COOL-ELC-50", name: "ELC coolant 50/50 (10 L)", onHand: 4, min: 3, k: "ontime", loc: "Thompson shop · A3" },
];

export const fuelStats: FuelRouteStat[] = [
  { unit: "U-01", l100: "38.9 L/100km", idlePct: "21%", routeAdherence: "—", k: "over" },
  { unit: "U-02", l100: "36.2 L/100km", idlePct: "11%", routeAdherence: "97%", k: "ontime" },
  { unit: "U-03", l100: "37.0 L/100km", idlePct: "14%", routeAdherence: "95%", k: "ontime" },
  { unit: "U-04", l100: "14.1 L/100km", idlePct: "9%", routeAdherence: "98%", k: "ontime" },
  { unit: "U-05", l100: "16.8 L/100km", idlePct: "19%", routeAdherence: "91%", k: "soon" },
  { unit: "U-06", l100: "15.2 L/100km", idlePct: "12%", routeAdherence: "96%", k: "ontime" },
];

export const clients: Client[] = [
  {
    id: 1,
    name: "Alamos Gold",
    svc: "alamos",
    tag: "Corporate",
    renew: "Renews in 21d",
    rk: "soon",
    term: "2024-04 → 2026-07",
    rate: "Contract · crew shuttle",
    po: "PO-AG-2261 structure",
    gst: "GST 5% · no PST",
    notes: "Contractor clearance required per driver (June 2026 incident).",
  },
  {
    id: 2,
    name: "NIHB Medical Transport",
    svc: "nihb",
    tag: "Program",
    renew: "Active program",
    rk: "ontime",
    term: "Ongoing",
    rate: "NIHB tier schedule",
    po: "Voucher-based",
    gst: "Direct-billed · patient $0",
    notes: "Prior-approved voucher = confirmed demand. Escorts travel free.",
  },
  {
    id: 3,
    name: "Keewatin Tribal Council",
    svc: "charter",
    tag: "Charter",
    renew: "Renews in 140d",
    rk: "ontime",
    term: "2025-01 → 2026-12",
    rate: "Charter · per-run",
    po: "CH series",
    gst: "GST 5%",
    notes: "Occasional multi-community charters.",
  },
  {
    id: 4,
    name: "Community Riders (Corridor)",
    svc: "community",
    tag: "Individuals",
    renew: "Fare book",
    rk: "ontime",
    term: "—",
    rate: "Community fare · demand-activated",
    po: "—",
    gst: "GST 5%",
    notes: "4-passenger minimum unless guaranteed or NIHB voucher.",
  },
  {
    id: 5,
    name: "Miller the Mover",
    svc: "cargo",
    tag: "Vendor / Partner",
    renew: "Partner agreement",
    rk: "ontime",
    term: "Ongoing",
    rate: "Driver-supply partner",
    po: "—",
    gst: "—",
    notes: "Supplies drivers into the roster (tagged by source tenant).",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-2041",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    amt: "$3,842.00",
    code: "ZBB-CREW-01",
    status: "Sent",
    sk: "info",
    qbo: "Matched",
    age: "12d",
  },
  {
    id: "INV-2042",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    amt: "$4,120.00",
    code: "ZBB-CREW-01",
    status: "Draft",
    sk: "soon",
    qbo: "Not synced",
    age: "—",
  },
  {
    id: "INV-2038",
    client: "Keewatin Tribal Council",
    po: "CH-3390",
    amt: "$1,284.00",
    code: "ZBB-CHTR-02",
    status: "Paid",
    sk: "ontime",
    qbo: "Matched",
    age: "Paid",
  },
  {
    id: "INV-2033",
    client: "NIHB Medical",
    po: "VCH-88041",
    amt: "$612.00",
    code: "ZBB-NIHB-01",
    status: "Sent",
    sk: "info",
    qbo: "Matched",
    age: "18d",
  },
  {
    id: "INV-2029",
    client: "Alamos Gold",
    po: "PO-AG-2255",
    amt: "$2,905.00",
    code: "ZBB-CREW-01",
    status: "Overdue",
    sk: "over",
    qbo: "Matched",
    age: "63d",
  },
  {
    id: "INV-2044",
    client: "Community Riders",
    po: "—",
    amt: "$268.00",
    code: "ZBB-COMM-01",
    status: "Draft",
    sk: "soon",
    qbo: "Not synced",
    age: "—",
  },
  {
    id: "INV-2031",
    client: "NIHB Medical",
    po: "VCH-87990",
    amt: "$540.00",
    code: "ZBB-NIHB-01",
    status: "Paid",
    sk: "ontime",
    qbo: "Matched",
    age: "Paid",
  },
  {
    id: "INV-2045",
    client: "Keewatin Tribal Council",
    po: "CH-3402",
    amt: "$1,510.00",
    code: "ZBB-CHTR-02",
    status: "Draft",
    sk: "soon",
    qbo: "Unmatched payment",
    age: "—",
  },
];

export const riders: Rider[] = [
  {
    id: 1,
    name: "Eleanor Bighetty",
    home: "South Indian Lake",
    prog: "NIHB",
    last: "Jul 7",
    phone: "(204) 555-0233",
    pc: "R0B 1N0",
    voucher: "VCH-88041 · active",
    escort: "1 authorized",
    noshow: "0",
    needs: "Wheelchair-accessible",
  },
  {
    id: 2,
    name: "Marcel Dumas",
    home: "Leaf Rapids",
    prog: "Community",
    last: "Jul 2",
    phone: "(204) 555-0288",
    pc: "R0B 1W0",
    voucher: "—",
    escort: "—",
    noshow: "1",
    needs: "None",
  },
  {
    id: 3,
    name: "Sarah Linklater",
    home: "Lynn Lake",
    prog: "NIHB",
    last: "Jun 28",
    phone: "(204) 555-0301",
    pc: "R0B 0W0",
    voucher: "VCH-87990 · used",
    escort: "—",
    noshow: "0",
    needs: "None",
  },
  {
    id: 4,
    name: "George Moose",
    home: "Black Sturgeon Falls",
    prog: "Community",
    last: "Jun 30",
    phone: "(204) 555-0319",
    pc: "R8N 1P4",
    voucher: "—",
    escort: "—",
    noshow: "0",
    needs: "Mobility aid",
  },
  {
    id: 5,
    name: "Priya Sandhu",
    home: "Thompson",
    prog: "Community",
    last: "Jul 5",
    phone: "(204) 555-0344",
    pc: "R8N 0C8",
    voucher: "—",
    escort: "—",
    noshow: "2",
    needs: "None",
  },
];

export const incidents: Incident[] = [
  {
    id: "INC-118",
    sev: "Critical",
    sk: "over",
    status: "Investigating",
    date: "Jul 6",
    driver: "A. Nepinak",
    vehicle: "U-01",
    trip: "TR-4790",
    summary:
      "Steering fault reported mid-corridor; vehicle taken out of service.",
  },
  {
    id: "INC-117",
    sev: "Moderate",
    sk: "soon",
    status: "Open",
    date: "Jul 5",
    driver: "R. Flett",
    vehicle: "U-05",
    trip: "TR-4772",
    summary: "Minor delay — road advisory PR-391 near Leaf Rapids.",
  },
  {
    id: "INC-115",
    sev: "Low",
    sk: "info",
    status: "Resolved",
    date: "Jul 2",
    driver: "J. Spence",
    vehicle: "U-04",
    trip: "TR-4740",
    summary: "Passenger no-show; documented for billing.",
  },
  {
    id: "FLT-062",
    sev: "Moderate",
    sk: "soon",
    status: "Open",
    date: "Jul 7",
    driver: "—",
    vehicle: "U-06",
    trip: "—",
    summary: "Brake wear flagged on DVIR; scheduled for service.",
  },
];
