import type {
  Client,
  Driver,
  FleetVehicle,
  Incident,
  Invoice,
  Rider,
  Trip,
} from "./types";

export const communities = [
  "Thompson",
  "Leaf Rapids",
  "Lynn Lake",
  "South Indian Lake",
  "Black Sturgeon Falls",
];

export const trips: Trip[] = [
  {
    id: "TR-4821",
    date: "Jul 7",
    win: "06:30 → 09:55",
    svc: "alamos",
    from: "Thompson",
    to: "Lynn Lake",
    stops: ["Thompson", "Leaf Rapids", "Lynn Lake"],
    km: 198,
    driver: "D. Chartrand",
    vehicle: "INT-3000 · U-02",
    cap: "18 / 24",
    status: "In progress",
    sk: "info",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    open: false,
  },
  {
    id: "TR-4822",
    date: "Jul 7",
    win: "07:15 → 09:40",
    svc: "nihb",
    from: "South Indian Lake",
    to: "Thompson",
    stops: ["South Indian Lake", "Thompson"],
    km: 220,
    driver: "M. Okimaw",
    vehicle: "Transit T-150 · U-04",
    cap: "3 / 7",
    status: "In progress",
    sk: "info",
    client: "NIHB",
    po: "VCH-88041",
    open: false,
  },
  {
    id: "TR-4823",
    date: "Jul 7",
    win: "11:00 → 14:20",
    svc: "community",
    from: "Leaf Rapids",
    to: "Thompson",
    stops: ["Leaf Rapids", "Thompson"],
    km: 174,
    driver: null,
    vehicle: "Transit T-150 · U-05",
    cap: "4 / 7",
    status: "Open — needs coverage",
    sk: "soon",
    client: "Community",
    po: "—",
    open: true,
  },
  {
    id: "TR-4824",
    date: "Jul 7",
    win: "13:30 → 16:10",
    svc: "alamos",
    from: "Lynn Lake",
    to: "Thompson",
    stops: ["Lynn Lake", "Leaf Rapids", "Thompson"],
    km: 198,
    driver: "D. Chartrand",
    vehicle: "INT-3000 · U-02",
    cap: "empty return",
    status: "Empty leg available",
    sk: "off",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    open: false,
  },
  {
    id: "TR-4825",
    date: "Jul 7",
    win: "15:00 → 17:35",
    svc: "grocery",
    from: "Thompson",
    to: "Black Sturgeon Falls",
    stops: ["Thompson", "Black Sturgeon Falls"],
    km: 142,
    driver: null,
    vehicle: "Transit T-150 · U-06",
    cap: "load 62%",
    status: "Open — needs coverage",
    sk: "soon",
    client: "Grocery Program",
    po: "—",
    open: true,
  },
  {
    id: "TR-4826",
    date: "Jul 7",
    win: "16:45 → 20:05",
    svc: "charter",
    from: "Thompson",
    to: "Lynn Lake",
    stops: ["Thompson", "Lynn Lake"],
    km: 198,
    driver: "K. Beardy",
    vehicle: "INT-3000 · U-03",
    cap: "11 / 24",
    status: "Scheduled",
    sk: "ontime",
    client: "Keewatin Tribal Council",
    po: "CH-3390",
    open: false,
  },
  {
    id: "TR-4818",
    date: "Jul 7",
    win: "05:10 → 08:30",
    svc: "community",
    from: "Black Sturgeon Falls",
    to: "Thompson",
    stops: ["Black Sturgeon Falls", "Thompson"],
    km: 142,
    driver: "J. Spence",
    vehicle: "Transit T-150 · U-04",
    cap: "6 / 7",
    status: "Completed",
    sk: "ontime",
    client: "Community",
    po: "—",
    open: false,
  },
  {
    id: "TR-4827",
    date: "Jul 7",
    win: "18:20 → 21:00",
    svc: "cargo",
    from: "Thompson",
    to: "Leaf Rapids",
    stops: ["Thompson", "Leaf Rapids"],
    km: 96,
    driver: null,
    vehicle: "unassigned",
    cap: "—",
    status: "Open — no eligible driver",
    sk: "over",
    client: "Parcel",
    po: "—",
    open: true,
  },
];

export const drivers: Driver[] = [
  {
    id: 1,
    name: "D. Chartrand",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    hos: "4h 20m",
    hk: "soon",
    lic: "Class 4 · exp 2027-03",
    lk: "ontime",
    dvir: "Passed",
    clr: ["Alamos ✓", "NIHB ✓"],
    phone: "(204) 555-0148",
    trips: 214,
  },
  {
    id: 2,
    name: "M. Okimaw",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    hos: "6h 05m",
    hk: "ontime",
    lic: "Class 4 · exp 2026-11",
    lk: "ontime",
    dvir: "Passed",
    clr: ["NIHB ✓"],
    phone: "(204) 555-0192",
    trips: 98,
  },
  {
    id: 3,
    name: "K. Beardy",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    hos: "9h 40m",
    hk: "ontime",
    lic: "Class 4 · exp 2028-01",
    lk: "ontime",
    dvir: "Passed",
    clr: ["Alamos ✓", "NIHB ✓"],
    phone: "(204) 555-0177",
    trips: 301,
  },
  {
    id: 4,
    name: "J. Spence",
    src: "Northern Link",
    duty: "Off duty",
    dk: "off",
    hos: "0h 00m",
    hk: "off",
    lic: "Class 4 · exp 2026-08",
    lk: "soon",
    dvir: "Passed",
    clr: ["NIHB ✓"],
    phone: "(204) 555-0110",
    trips: 156,
  },
  {
    id: 5,
    name: "T. Miller",
    src: "Miller the Mover",
    duty: "On duty",
    dk: "info",
    hos: "2h 15m",
    hk: "soon",
    lic: "Class 4 · exp 2027-06",
    lk: "ontime",
    dvir: "Passed",
    clr: ["Alamos ✓"],
    phone: "(204) 555-0201",
    trips: 44,
  },
  {
    id: 6,
    name: "R. Flett",
    src: "Northern Link",
    duty: "On duty",
    dk: "info",
    hos: "7h 30m",
    hk: "ontime",
    lic: "Class 4 · exp 2026-07",
    lk: "over",
    dvir: "Passed",
    clr: [],
    phone: "(204) 555-0139",
    trips: 187,
  },
  {
    id: 7,
    name: "A. Nepinak",
    src: "Miller the Mover",
    duty: "Deactivated",
    dk: "over",
    hos: "—",
    hk: "off",
    lic: "Class 4 · exp 2027-09",
    lk: "ontime",
    dvir: "Under review",
    clr: [],
    phone: "(204) 555-0166",
    trips: 72,
  },
];

export const fleet: FleetVehicle[] = [
  {
    id: 1,
    unit: "U-02",
    model: "International 3000",
    seats: 24,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "NSC-11 due in 34d",
    ik: "ontime",
    plate: "MB · GHT 402",
    vin: "1HVBBAAN…4471",
    licReq: "Class 4",
    periodic: true,
  },
  {
    id: 2,
    unit: "U-03",
    model: "International 3000",
    seats: 24,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "NSC-11 due in 9d",
    ik: "soon",
    plate: "MB · GHT 418",
    vin: "1HVBBAAN…5522",
    licReq: "Class 4",
    periodic: true,
  },
  {
    id: 3,
    unit: "U-04",
    model: "Ford Transit T-150",
    seats: 7,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "Trip-inspection only",
    ik: "ontime",
    plate: "MB · FRT 771",
    vin: "1FTBW2CM…9013",
    licReq: "Class 4",
    periodic: false,
  },
  {
    id: 4,
    unit: "U-05",
    model: "Ford Transit T-150",
    seats: 7,
    status: "Active",
    sk: "info",
    dvir: "Passed today",
    dk: "ontime",
    insp: "Trip-inspection only",
    ik: "ontime",
    plate: "MB · FRT 802",
    vin: "1FTBW2CM…9188",
    licReq: "Class 4",
    periodic: false,
  },
  {
    id: 5,
    unit: "U-06",
    model: "Ford Transit T-150",
    seats: 7,
    status: "In maintenance",
    sk: "soon",
    dvir: "Passed today",
    dk: "ontime",
    insp: "Brake service",
    ik: "soon",
    plate: "MB · FRT 815",
    vin: "1FTBW2CM…9204",
    licReq: "Class 4",
    periodic: false,
  },
  {
    id: 6,
    unit: "U-01",
    model: "International 3000",
    seats: 24,
    status: "Out of service",
    sk: "over",
    dvir: "DVIR FAILED",
    dk: "over",
    insp: "Steering fault — critical",
    ik: "over",
    plate: "MB · GHT 390",
    vin: "1HVBBAAN…3310",
    licReq: "Class 4",
    periodic: true,
  },
];

export const clients: Client[] = [
  {
    id: 1,
    name: "Alamos Gold",
    svc: "alamos",
    tag: "Corporate",
    renew: "Renews in 21d",
    rk: "soon",
    term: "2024-04 → 2026-07",
    rate: "Contract · crew shuttle",
    po: "PO-AG-2261 structure",
    gst: "GST 5% · no PST",
    contacts: [
      ["Quinton Falk", "Site operations"],
      ["Brendan D'Allaire", "Contract renewal"],
      ["Daniel Lavallée", "Compliance"],
      ["LL-ContractorClearances", "Clearance desk"],
      ["Accounts Payable", "Invoice routing"],
    ],
    notes: "Contractor clearance required per driver (June 2026 incident).",
  },
  {
    id: 2,
    name: "NIHB Medical Transport",
    svc: "nihb",
    tag: "Program",
    renew: "Active program",
    rk: "ontime",
    term: "Ongoing",
    rate: "NIHB tier schedule",
    po: "Voucher-based",
    gst: "Direct-billed · patient $0",
    contacts: [
      ["NIHB Regional Office", "Voucher authorization"],
      ["Patient Travel Desk", "Booking coordination"],
    ],
    notes: "Prior-approved voucher = confirmed demand. Escorts travel free.",
  },
  {
    id: 3,
    name: "Keewatin Tribal Council",
    svc: "charter",
    tag: "Charter",
    renew: "Renews in 140d",
    rk: "ontime",
    term: "2025-01 → 2026-12",
    rate: "Charter · per-run",
    po: "CH series",
    gst: "GST 5%",
    contacts: [["Council Transport Lead", "Charter requests"]],
    notes: "Occasional multi-community charters.",
  },
  {
    id: 4,
    name: "Community Riders (Corridor)",
    svc: "community",
    tag: "Individuals",
    renew: "Fare book",
    rk: "ontime",
    term: "—",
    rate: "Community fare · demand-activated",
    po: "—",
    gst: "GST 5%",
    contacts: [["—", "Individual bookings"]],
    notes: "4-passenger minimum unless guaranteed or NIHB voucher.",
  },
  {
    id: 5,
    name: "Miller the Mover",
    svc: "cargo",
    tag: "Vendor / Partner",
    renew: "Partner agreement",
    rk: "ontime",
    term: "Ongoing",
    rate: "Driver-supply partner",
    po: "—",
    gst: "—",
    contacts: [["Dispatch Liaison", "Driver supply"]],
    notes: "Supplies drivers into the roster (tagged by source tenant).",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-2041",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    amt: "$3,842.00",
    code: "ZBB-CREW-01",
    status: "Sent",
    sk: "info",
    qbo: "Matched",
    age: "12d",
  },
  {
    id: "INV-2042",
    client: "Alamos Gold",
    po: "PO-AG-2261",
    amt: "$4,120.00",
    code: "ZBB-CREW-01",
    status: "Draft",
    sk: "soon",
    qbo: "Not synced",
    age: "—",
  },
  {
    id: "INV-2038",
    client: "Keewatin Tribal Council",
    po: "CH-3390",
    amt: "$1,284.00",
    code: "ZBB-CHTR-02",
    status: "Paid",
    sk: "ontime",
    qbo: "Matched",
    age: "Paid",
  },
  {
    id: "INV-2033",
    client: "NIHB Medical",
    po: "VCH-88041",
    amt: "$612.00",
    code: "ZBB-NIHB-01",
    status: "Sent",
    sk: "info",
    qbo: "Matched",
    age: "18d",
  },
  {
    id: "INV-2029",
    client: "Alamos Gold",
    po: "PO-AG-2255",
    amt: "$2,905.00",
    code: "ZBB-CREW-01",
    status: "Overdue",
    sk: "over",
    qbo: "Matched",
    age: "63d",
  },
  {
    id: "INV-2044",
    client: "Community Riders",
    po: "—",
    amt: "$268.00",
    code: "ZBB-COMM-01",
    status: "Draft",
    sk: "soon",
    qbo: "Not synced",
    age: "—",
  },
  {
    id: "INV-2031",
    client: "NIHB Medical",
    po: "VCH-87990",
    amt: "$540.00",
    code: "ZBB-NIHB-01",
    status: "Paid",
    sk: "ontime",
    qbo: "Matched",
    age: "Paid",
  },
  {
    id: "INV-2045",
    client: "Keewatin Tribal Council",
    po: "CH-3402",
    amt: "$1,510.00",
    code: "ZBB-CHTR-02",
    status: "Draft",
    sk: "soon",
    qbo: "Unmatched payment",
    age: "—",
  },
];

export const riders: Rider[] = [
  {
    id: 1,
    name: "Eleanor Bighetty",
    home: "South Indian Lake",
    prog: "NIHB",
    last: "Jul 7",
    phone: "(204) 555-0233",
    pc: "R0B 1N0",
    voucher: "VCH-88041 · active",
    escort: "1 authorized",
    noshow: "0",
    needs: "Wheelchair-accessible",
  },
  {
    id: 2,
    name: "Marcel Dumas",
    home: "Leaf Rapids",
    prog: "Community",
    last: "Jul 2",
    phone: "(204) 555-0288",
    pc: "R0B 1W0",
    voucher: "—",
    escort: "—",
    noshow: "1",
    needs: "None",
  },
  {
    id: 3,
    name: "Sarah Linklater",
    home: "Lynn Lake",
    prog: "NIHB",
    last: "Jun 28",
    phone: "(204) 555-0301",
    pc: "R0B 0W0",
    voucher: "VCH-87990 · used",
    escort: "—",
    noshow: "0",
    needs: "None",
  },
  {
    id: 4,
    name: "George Moose",
    home: "Black Sturgeon Falls",
    prog: "Community",
    last: "Jun 30",
    phone: "(204) 555-0319",
    pc: "R8N 1P4",
    voucher: "—",
    escort: "—",
    noshow: "0",
    needs: "Mobility aid",
  },
  {
    id: 5,
    name: "Priya Sandhu",
    home: "Thompson",
    prog: "Community",
    last: "Jul 5",
    phone: "(204) 555-0344",
    pc: "R8N 0C8",
    voucher: "—",
    escort: "—",
    noshow: "2",
    needs: "None",
  },
];

export const incidents: Incident[] = [
  {
    id: "INC-118",
    sev: "Critical",
    sk: "over",
    status: "Investigating",
    date: "Jul 6",
    driver: "A. Nepinak",
    vehicle: "U-01",
    trip: "TR-4790",
    summary:
      "Steering fault reported mid-corridor; vehicle taken out of service.",
  },
  {
    id: "INC-117",
    sev: "Moderate",
    sk: "soon",
    status: "Open",
    date: "Jul 5",
    driver: "R. Flett",
    vehicle: "U-05",
    trip: "TR-4772",
    summary: "Minor delay — road advisory PR-391 near Leaf Rapids.",
  },
  {
    id: "INC-115",
    sev: "Low",
    sk: "info",
    status: "Resolved",
    date: "Jul 2",
    driver: "J. Spence",
    vehicle: "U-04",
    trip: "TR-4740",
    summary: "Passenger no-show; documented for billing.",
  },
  {
    id: "FLT-062",
    sev: "Moderate",
    sk: "soon",
    status: "Open",
    date: "Jul 7",
    driver: "—",
    vehicle: "U-06",
    trip: "—",
    summary: "Brake wear flagged on DVIR; scheduled for service.",
  },
];
