// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthernLink.Trips.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthernLink.Trips.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TripsDbContext))]
    [Migration("20260715112627_InitialTripsSchema")]
    partial class InitialTripsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trips")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.AggregateSnapshot", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("AggregateId", "Version");

                    b.HasIndex("TenantId", "AggregateType", "CreatedAtUtc");

                    b.ToTable("aggregate_snapshots", "trips");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.EventJournalEntry", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Position"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Position");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AggregateId", "AggregateVersion");

                    b.ToTable("event_journal", "trips");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.OutboxMessage", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Position"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("routing_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Position");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at_utc IS NULL");

                    b.ToTable("outbox_messages", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Manifests.TripManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllCargoSecured")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("all_cargo_secured");

                    b.Property<bool>("AllSeatbeltsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("all_seatbelts_verified");

                    b.Property<string>("ArrivalTime")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("arrival_time");

                    b.PrimitiveCollection<List<bool>>("Attestations")
                        .IsRequired()
                        .HasColumnType("boolean[]")
                        .HasColumnName("attestations");

                    b.Property<DateTimeOffset>("CertifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certified_at");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DepartureTime")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("departure_time");

                    b.Property<string>("Direction")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<string>("DriverLicenceNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("driver_licence_no");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("driver_name");

                    b.Property<string>("DriverSignatureName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("driver_signature_name");

                    b.Property<DateTimeOffset?>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entered_by");

                    b.Property<bool>("FuelAdded")
                        .HasColumnType("boolean")
                        .HasColumnName("fuel_added");

                    b.Property<decimal?>("FuelCostCad")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("fuel_cost_cad");

                    b.Property<string>("FuelLevel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fuel_level");

                    b.Property<decimal?>("FuelLitres")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("fuel_litres");

                    b.PrimitiveCollection<List<string>>("Issues")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("issues");

                    b.Property<string>("LicencePlate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("licence_plate");

                    b.Property<bool>("NoIssues")
                        .HasColumnType("boolean")
                        .HasColumnName("no_issues");

                    b.Property<int?>("OdometerEndKm")
                        .HasColumnType("integer")
                        .HasColumnName("odometer_end_km");

                    b.Property<int?>("OdometerStartKm")
                        .HasColumnType("integer")
                        .HasColumnName("odometer_start_km");

                    b.Property<string>("RoadAdvisories")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("road_advisories");

                    b.PrimitiveCollection<string[]>("RoadConditions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("road_conditions");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<string>("TemperatureC")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("temperature_c");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TotalKm")
                        .HasColumnType("integer")
                        .HasColumnName("total_km");

                    b.Property<DateOnly>("TripDate")
                        .HasColumnType("date")
                        .HasColumnName("trip_date");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trip_number");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.PrimitiveCollection<string[]>("Weather")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("weather");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TripNumber");

                    b.HasIndex("TenantId", "Unit");

                    b.ToTable("trip_manifests", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Manifests.TripManifest", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.ManifestCargoItem", "Cargo", b1 =>
                        {
                            b1.Property<Guid>("TripManifestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("ChargeCad")
                                .HasPrecision(12, 2);

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<bool>("Hazmat");

                            b1.Property<string>("OwnerRecipient");

                            b1.Property<bool>("Secured");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(8, 2);

                            b1.HasKey("TripManifestId", "__synthesizedOrdinal");

                            b1.ToTable("trip_manifests", "trips");

                            b1.ToJson("cargo");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestId");
                        });

                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.ManifestPassenger", "Passengers", b1 =>
                        {
                            b1.Property<Guid>("TripManifestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("BoardedOff");

                            b1.Property<bool>("BoardedOn");

                            b1.Property<string>("Contact");

                            b1.Property<string>("Dropoff");

                            b1.Property<bool>("IdVerified");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Pickup");

                            b1.HasKey("TripManifestId", "__synthesizedOrdinal");

                            b1.ToTable("trip_manifests", "trips");

                            b1.ToJson("passengers");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestId");
                        });

                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.PostTripChecklistItem", "PostTripItems", b1 =>
                        {
                            b1.Property<Guid>("TripManifestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Item")
                                .IsRequired();

                            b1.Property<bool>("Ok");

                            b1.HasKey("TripManifestId", "__synthesizedOrdinal");

                            b1.ToTable("trip_manifests", "trips");

                            b1.ToJson("post_trip_items");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestId");
                        });

                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.PreTripChecklistItem", "PreTripItems", b1 =>
                        {
                            b1.Property<Guid>("TripManifestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Group")
                                .IsRequired();

                            b1.Property<string>("Item")
                                .IsRequired();

                            b1.Property<string>("Note");

                            b1.Property<string>("Severity");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("TripManifestId", "__synthesizedOrdinal");

                            b1.ToTable("trip_manifests", "trips");

                            b1.ToJson("pre_trip_items");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestId");
                        });

                    b.Navigation("Cargo");

                    b.Navigation("Passengers");

                    b.Navigation("PostTripItems");

                    b.Navigation("PreTripItems");
                });
#pragma warning restore 612, 618
        }
    }
}
