// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthernLink.Trips.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthernLink.Trips.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TripsDbContext))]
    partial class TripsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trips")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.AggregateSnapshot", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("AggregateId", "Version");

                    b.HasIndex("TenantId", "AggregateType", "CreatedAtUtc");

                    b.ToTable("aggregate_snapshots", "trips");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.EventJournalEntry", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Position"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Position");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AggregateId", "AggregateVersion");

                    b.ToTable("event_journal", "trips");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.OutboxMessage", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Position"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("routing_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Position");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at_utc IS NULL");

                    b.ToTable("outbox_messages", "trips");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Projections.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("projection_name");

                    b.Property<long>("LastPosition")
                        .HasColumnType("bigint")
                        .HasColumnName("last_position");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ProjectionName");

                    b.ToTable("projection_checkpoints", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Application.Integration.ClientLookup", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ClientId");

                    b.HasIndex("TenantId");

                    b.ToTable("client_lookup", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Application.Integration.DriverLookup", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("LicenceClass")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("licence_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DriverId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("driver_lookup", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Application.Integration.VehicleLookup", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("RequiredLicenceClass")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("required_licence_class");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seating_capacity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("VehicleId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("vehicle_lookup", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Manifests.TripManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllCargoSecured")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("all_cargo_secured");

                    b.Property<bool>("AllSeatbeltsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("all_seatbelts_verified");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset?>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entered_by");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("TripDate")
                        .HasColumnType("date")
                        .HasColumnName("trip_date");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trip_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TripNumber");

                    b.ToTable("trip_manifests", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Routes.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("integer")
                        .HasColumnName("distance_km");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RequiredLicenceClass")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("required_licence_class");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("routes", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Schedules.ScheduleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CutoffNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cutoff_note");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("days_of_week");

                    b.Property<Guid?>("DefaultDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_driver_id");

                    b.Property<string>("DefaultVehicleUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_vehicle_unit");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("departure_time");

                    b.Property<int>("GenerationHorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("generation_horizon_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("ReturnDepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("return_departure_time");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SeatsCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seats_capacity");

                    b.Property<int?>("SeatsMinimum")
                        .HasColumnType("integer")
                        .HasColumnName("seats_minimum");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Active");

                    b.HasIndex("TenantId", "RouteId");

                    b.ToTable("schedule_templates", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Stops.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Active");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("stops", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancelled_reason");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DemandGuaranteed")
                        .HasColumnType("boolean")
                        .HasColumnName("demand_guaranteed");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<string>("Direction")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("integer")
                        .HasColumnName("distance_km");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("driver_name");

                    b.Property<bool>("HasPostTripInspection")
                        .HasColumnType("boolean")
                        .HasColumnName("has_post_trip_inspection");

                    b.Property<bool>("IsEmptyLeg")
                        .HasColumnType("boolean")
                        .HasColumnName("is_empty_leg");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("manifest_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origin");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("po_number");

                    b.Property<string>("RoundTripKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("round_trip_key");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route_name");

                    b.Property<Guid?>("ScheduleTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_template_id");

                    b.Property<int?>("SeatsCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seats_capacity");

                    b.Property<int>("SeatsConfirmed")
                        .HasColumnType("integer")
                        .HasColumnName("seats_confirmed");

                    b.Property<int?>("SeatsMinimum")
                        .HasColumnType("integer")
                        .HasColumnName("seats_minimum");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trip_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vehicle_unit");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_end");

                    b.Property<TimeOnly>("WindowStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ClientId");

                    b.HasIndex("TenantId", "DriverId");

                    b.HasIndex("TenantId", "ServiceDate");

                    b.HasIndex("TenantId", "TripNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "ScheduleTemplateId", "ServiceDate", "Direction")
                        .IsUnique();

                    b.ToTable("trips", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.RouteReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("integer")
                        .HasColumnName("distance_km");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("RequiredLicenceClass")
                        .HasColumnType("text")
                        .HasColumnName("required_licence_class");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("rm_routes", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.ScheduleTemplateReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CutoffNote")
                        .HasColumnType("text")
                        .HasColumnName("cutoff_note");

                    b.PrimitiveCollection<List<string>>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("days_of_week");

                    b.Property<Guid?>("DefaultDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_driver_id");

                    b.Property<string>("DefaultVehicleUnit")
                        .HasColumnType("text")
                        .HasColumnName("default_vehicle_unit");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("departure_time");

                    b.Property<int>("GenerationHorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("generation_horizon_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("ReturnDepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("return_departure_time");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteName")
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<int>("SeatsCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seats_capacity");

                    b.Property<int?>("SeatsMinimum")
                        .HasColumnType("integer")
                        .HasColumnName("seats_minimum");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("rm_schedule_templates", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.StopReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Active");

                    b.ToTable("rm_stops", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.TripManifestReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllCargoSecured")
                        .HasColumnType("text")
                        .HasColumnName("all_cargo_secured");

                    b.Property<bool>("AllSeatbeltsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("all_seatbelts_verified");

                    b.Property<string>("Client")
                        .HasColumnType("text")
                        .HasColumnName("client");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset?>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<string>("EnteredBy")
                        .HasColumnType("text")
                        .HasColumnName("entered_by");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("TripDate")
                        .HasColumnType("date")
                        .HasColumnName("trip_date");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_number");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("rm_trip_manifests", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.TripReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelledReason")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_reason");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DemandGuaranteed")
                        .HasColumnType("boolean")
                        .HasColumnName("demand_guaranteed");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("integer")
                        .HasColumnName("distance_km");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverName")
                        .HasColumnType("text")
                        .HasColumnName("driver_name");

                    b.Property<bool>("HasPostTripInspection")
                        .HasColumnType("boolean")
                        .HasColumnName("has_post_trip_inspection");

                    b.Property<bool>("IsEmptyLeg")
                        .HasColumnType("boolean")
                        .HasColumnName("is_empty_leg");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("manifest_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("PoNumber")
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<string>("RoundTripKey")
                        .HasColumnType("text")
                        .HasColumnName("round_trip_key");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<Guid?>("ScheduleTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_template_id");

                    b.Property<int?>("SeatsCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seats_capacity");

                    b.Property<int>("SeatsConfirmed")
                        .HasColumnType("integer")
                        .HasColumnName("seats_confirmed");

                    b.Property<int?>("SeatsMinimum")
                        .HasColumnType("integer")
                        .HasColumnName("seats_minimum");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleUnit")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_unit");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_end");

                    b.Property<TimeOnly>("WindowStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ServiceDate");

                    b.ToTable("rm_trips", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.TripNumberCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.HasKey("TenantId");

                    b.ToTable("trip_number_counters", "trips");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Manifests.TripManifest", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.ManifestCargoItem", "Cargo", b1 =>
                        {
                            b1.Property<Guid>("TripManifestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("ChargeCad")
                                .HasPrecision(12, 2);

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<bool>("Hazmat");

                            b1.Property<string>("OwnerRecipient");

                            b1.Property<bool>("Secured");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(8, 2);

                            b1.HasKey("TripManifestId", "__synthesizedOrdinal");

                            b1.ToTable("trip_manifests", "trips");

                            b1.ToJson("cargo");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestId");
                        });

                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.ManifestPassenger", "Passengers", b1 =>
                        {
                            b1.Property<Guid>("TripManifestId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("BoardedOff");

                            b1.Property<bool>("BoardedOn");

                            b1.Property<string>("Contact");

                            b1.Property<Guid?>("DropoffStopId");

                            b1.Property<string>("DropoffStopName");

                            b1.Property<bool>("IdVerified");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<Guid?>("PickupStopId");

                            b1.Property<string>("PickupStopName");

                            b1.HasKey("TripManifestId", "__synthesizedOrdinal");

                            b1.ToTable("trip_manifests", "trips");

                            b1.ToJson("passengers");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestId");
                        });

                    b.Navigation("Cargo");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Routes.Route", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Routes.RouteStop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("RouteId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("Latitude");

                            b1.Property<double?>("Longitude");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Order");

                            b1.Property<Guid?>("StopId");

                            b1.HasKey("RouteId", "__synthesizedOrdinal");

                            b1.ToTable("routes", "trips");

                            b1.ToJson("stops");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Stops.Stop", b =>
                {
                    b.OwnsOne("NorthernLink.Trips.Domain.Stops.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StopId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("country");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("province");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("StopId");

                            b1.ToTable("stops", "trips");

                            b1.WithOwner()
                                .HasForeignKey("StopId");
                        });

                    b.OwnsOne("NorthernLink.Trips.Domain.Stops.Coordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("StopId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("StopId");

                            b1.ToTable("stops", "trips");

                            b1.WithOwner()
                                .HasForeignKey("StopId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Coordinate")
                        .IsRequired();
                });

            modelBuilder.Entity("NorthernLink.Trips.Domain.Trips.Trip", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Routes.RouteStop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("TripId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("Latitude");

                            b1.Property<double?>("Longitude");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Order");

                            b1.Property<Guid?>("StopId");

                            b1.HasKey("TripId", "__synthesizedOrdinal");

                            b1.ToTable("trips", "trips");

                            b1.ToJson("stops");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.RouteReadModel", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Routes.RouteStop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("RouteReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("Latitude");

                            b1.Property<double?>("Longitude");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Order");

                            b1.Property<Guid?>("StopId");

                            b1.HasKey("RouteReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("rm_routes", "trips");

                            b1.ToJson("stops");

                            b1.WithOwner()
                                .HasForeignKey("RouteReadModelId");
                        });

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.TripManifestReadModel", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.ManifestCargoItem", "Cargo", b1 =>
                        {
                            b1.Property<Guid>("TripManifestReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("ChargeCad")
                                .HasPrecision(12, 2);

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<bool>("Hazmat");

                            b1.Property<string>("OwnerRecipient");

                            b1.Property<bool>("Secured");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(8, 2);

                            b1.HasKey("TripManifestReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("rm_trip_manifests", "trips");

                            b1.ToJson("cargo");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestReadModelId");
                        });

                    b.OwnsMany("NorthernLink.Trips.Domain.Manifests.ManifestPassenger", "Passengers", b1 =>
                        {
                            b1.Property<Guid>("TripManifestReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("BoardedOff");

                            b1.Property<bool>("BoardedOn");

                            b1.Property<string>("Contact");

                            b1.Property<Guid?>("DropoffStopId");

                            b1.Property<string>("DropoffStopName");

                            b1.Property<bool>("IdVerified");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<Guid?>("PickupStopId");

                            b1.Property<string>("PickupStopName");

                            b1.HasKey("TripManifestReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("rm_trip_manifests", "trips");

                            b1.ToJson("passengers");

                            b1.WithOwner()
                                .HasForeignKey("TripManifestReadModelId");
                        });

                    b.Navigation("Cargo");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("NorthernLink.Trips.Infrastructure.Persistence.ReadModels.TripReadModel", b =>
                {
                    b.OwnsMany("NorthernLink.Trips.Domain.Routes.RouteStop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("TripReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("Latitude");

                            b1.Property<double?>("Longitude");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Order");

                            b1.Property<Guid?>("StopId");

                            b1.HasKey("TripReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("rm_trips", "trips");

                            b1.ToJson("stops");

                            b1.WithOwner()
                                .HasForeignKey("TripReadModelId");
                        });

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
