using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using NorthernLink.Shared.HoursOfService;

namespace NorthernLink.Shared.Tests.HoursOfService;

/// <summary>
/// The on-disk shape of <c>hos-fixtures.json</c>. One object per case: the inputs, the
/// hand-written <see cref="Expect"/>, and the canonical <see cref="Snapshot"/> generated by
/// running the suite with <c>HOS_FIXTURES_UPDATE=1</c>. Property names are camelCase and enums
/// are member names, so the TypeScript mirror reads the same file unchanged.
/// </summary>
public sealed class FixtureCase
{
    public required string Id { get; set; }
    public required string Title { get; set; }
    public required string Regulation { get; set; }
    public required FixtureCalendar Calendar { get; set; }
    public long AsOfUnix { get; set; }
    public required DutyLedger Ledger { get; set; }
    public TripPlan? Plan { get; set; }
    public required FixtureExpect Expect { get; set; }
    public JsonNode? Snapshot { get; set; }
}

public sealed class FixtureCalendar
{
    public string TimeZoneId { get; set; } = HosCalendar.DefaultTimeZoneId;
    public int DayStartSecondsLocal { get; set; }
}

/// <summary>Hand-written expectations. Null means "not asserted".</summary>
public sealed class FixtureExpect
{
    /// <summary>Unsuppressed violations as <c>Rule@yyyy-MM-dd</c>, order-insensitive.</summary>
    public List<string> Violations { get; set; } = [];
    public List<string>? SuppressedViolations { get; set; }
    public bool CanDriveNow { get; set; }
    public List<BlockingReason> BlockingReasons { get; set; } = [];
    public HosBand Band { get; set; }
    public DutyStatus? CurrentStatus { get; set; }
    public int? RemainingDrivingTodaySeconds { get; set; }
    public int? RemainingOnDutyTodaySeconds { get; set; }
    public int? TightestRemainingSeconds { get; set; }
    public int? TodayDrivingSeconds { get; set; }
    public int? TodayOffDutySeconds { get; set; }
    public int? TodayOffDutyShortfallSeconds { get; set; }
    public long? ShiftStartUnix { get; set; }
    public bool? BetweenShifts { get; set; }
    public int? ShiftDrivingCeilingSeconds { get; set; }
    public int? CycleOnDutySeconds { get; set; }
    public long? CycleLastResetEndUnix { get; set; }
    public bool? CycleRecordsIncomplete { get; set; }
    public long? Rest24ExpiresAtUnix { get; set; }
    public int? PcTodayDecikm { get; set; }
    public List<string>? LedgerProblems { get; set; }
    public FixtureDayExpect? Day { get; set; }
    public FixtureProjectionExpect? Projection { get; set; }
}

public sealed class FixtureDayExpect
{
    public DateOnly Date { get; set; }
    public int? DrivingSeconds { get; set; }
    public int? OffDutySeconds { get; set; }
    public int? DailyOffRequiredSeconds { get; set; }
}

public sealed class FixtureProjectionExpect
{
    public bool Feasible { get; set; }
    public string? FirstBreach { get; set; }
    public int? RequiredOffBeforeStartSeconds { get; set; }
    public bool? RequiredOffIsNull { get; set; }
    public int? MarginAppliedSeconds { get; set; }
    public int? DailyOffStillNeededAfterPlanSeconds { get; set; }
    public bool? DailyOffAchievableAfterPlan { get; set; }
    public List<string>? Problems { get; set; }
}

public static class HosFixtureFile
{
    public const string FileName = "hos-fixtures.json";

    public static readonly JsonSerializerOptions Options = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never,
        AllowOutOfOrderMetadataProperties = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        Converters = { new JsonStringEnumConverter() },
    };

    /// <summary>The copy next to the test binaries (what the theory reads).</summary>
    public static string OutputPath => Path.Combine(AppContext.BaseDirectory, "HoursOfService", FileName);

    /// <summary>The source file in the repository (what the update mode rewrites).</summary>
    public static string SourcePath
    {
        get
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "NorthernLink.slnx")))
            {
                dir = dir.Parent;
            }

            if (dir is null)
            {
                throw new InvalidOperationException("Could not locate NorthernLink.slnx above the test output directory.");
            }

            return Path.Combine(dir.FullName, "tests", "NorthernLink.Shared.Tests", "HoursOfService", FileName);
        }
    }

    public static bool UpdateRequested =>
        Environment.GetEnvironmentVariable("HOS_FIXTURES_UPDATE") is "1" or "true";

    public static List<FixtureCase> Load(string path) =>
        JsonSerializer.Deserialize<List<FixtureCase>>(File.ReadAllText(path), Options)
        ?? throw new InvalidOperationException($"{path} is empty.");

    public static void Save(string path, IReadOnlyList<FixtureCase> cases) =>
        File.WriteAllText(path, JsonSerializer.Serialize(cases, Options) + "\n");

    public static HosCalendar CalendarOf(FixtureCase c) => new(c.Calendar.TimeZoneId, c.Calendar.DayStartSecondsLocal);

    /// <summary>The canonical output for a case: the evaluation, plus the projection when it has a plan.</summary>
    public static JsonNode Snapshot(FixtureCase c)
    {
        var cal = CalendarOf(c);
        var evaluation = HosEngine.Evaluate(c.Ledger, c.AsOfUnix, cal, new HosBands());
        var node = new JsonObject
        {
            ["evaluation"] = JsonSerializer.SerializeToNode(evaluation, Options),
        };
        if (c.Plan is not null)
        {
            node["projection"] = JsonSerializer.SerializeToNode(HosEngine.Project(c.Ledger, c.AsOfUnix, c.Plan, cal, new PlanningMargin()), Options);
        }

        return node;
    }
}
