// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthernLink.Fleet.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthernLink.Fleet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    partial class FleetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fleet")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthernLink.Fleet.Domain.Vehicles.RetirementCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("certificate_number");

                    b.Property<int>("FinalOdometerKm")
                        .HasColumnType("integer")
                        .HasColumnName("final_odometer_km");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at_utc");

                    b.Property<string>("RetirementReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("retirement_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_number");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("varchar(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "CertificateNumber")
                        .IsUnique();

                    b.ToTable("retirement_certificates", "fleet");
                });

            modelBuilder.Entity("NorthernLink.Fleet.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AcquisitionCostCad")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acquisition_cost_cad");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisposedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disposed_at_utc");

                    b.Property<int>("EndOfLifeKm")
                        .HasColumnType("integer")
                        .HasColumnName("end_of_life_km");

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("licence_plate");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<int>("OdometerKm")
                        .HasColumnType("integer")
                        .HasColumnName("odometer_km");

                    b.Property<string>("RequiredLicenceClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("required_licence_class");

                    b.Property<decimal?>("SalePriceCad")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sale_price_cad");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seating_capacity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("varchar(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UnitNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Vin")
                        .IsUnique();

                    b.ToTable("vehicles", "fleet");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.AggregateSnapshot", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("AggregateId", "Version");

                    b.HasIndex("TenantId", "AggregateType", "CreatedAtUtc");

                    b.ToTable("aggregate_snapshots", "fleet");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.EventJournalEntry", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Position"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Position");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AggregateId", "AggregateVersion");

                    b.ToTable("event_journal", "fleet");
                });

            modelBuilder.Entity("NorthernLink.Shared.Persistence.Auditing.OutboxMessage", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Position"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("routing_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Position");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at_utc IS NULL");

                    b.ToTable("outbox_messages", "fleet");
                });
#pragma warning restore 612, 618
        }
    }
}
